import { FieldDefinition } from '../types/fields.js';

export const SCHEMA_VERSION = '2024-06-18';

export const fieldDefinitions: FieldDefinition[] = [
  { id: 1, key: 'razao_social', label: 'Razão Social', section: 'CORE', group: 'A1', sourceKey: 'receita_cnpj' },
  { id: 2, key: 'nome_fantasia', label: 'Nome Fantasia', section: 'CORE', group: 'A1', sourceKey: 'receita_cnpj' },
  { id: 3, key: 'data_abertura', label: 'Data de Abertura', section: 'CORE', group: 'A1', sourceKey: 'receita_cnpj' },
  { id: 4, key: 'situacao_cadastral', label: 'Situação Cadastral', section: 'CORE', group: 'A1', sourceKey: 'receita_cnpj' },
  { id: 5, key: 'data_situacao_cadastral', label: 'Data da Situação Cadastral', section: 'CORE', group: 'A1', sourceKey: 'receita_cnpj' },
  { id: 6, key: 'motivo_situacao_cadastral', label: 'Motivo da Situação Cadastral', section: 'CORE', group: 'A1', sourceKey: 'receita_cnpj' },
  { id: 7, key: 'cnae_principal', label: 'CNAE Principal', section: 'CORE', group: 'A1', sourceKey: 'receita_cnpj' },
  { id: 8, key: 'descricao_cnae_principal', label: 'Descrição CNAE Principal', section: 'CORE', group: 'A1', sourceKey: 'receita_cnpj' },
  { id: 9, key: 'natureza_juridica', label: 'Natureza Jurídica', section: 'CORE', group: 'A1', sourceKey: 'receita_cnpj' },
  { id: 10, key: 'capital_social', label: 'Capital Social', section: 'CORE', group: 'A1', sourceKey: 'receita_cnpj' },
  { id: 11, key: 'porte_empresa', label: 'Porte da Empresa', section: 'CORE', group: 'A1', sourceKey: 'receita_cnpj' },
  { id: 12, key: 'matriz_filial', label: 'Matriz/Filial', section: 'CORE', group: 'A1', sourceKey: 'receita_cnpj' },
  { id: 13, key: 'data_inicio_atividade', label: 'Data de Início de Atividade', section: 'CORE', group: 'A1', sourceKey: 'receita_cnpj' },
  { id: 14, key: 'tipo_logradouro', label: 'Tipo de Logradouro', section: 'CORE', group: 'A2', sourceKey: 'receita_cnpj' },
  { id: 15, key: 'logradouro', label: 'Logradouro', section: 'CORE', group: 'A2', sourceKey: 'receita_cnpj' },
  { id: 16, key: 'numero', label: 'Número', section: 'CORE', group: 'A2', sourceKey: 'receita_cnpj' },
  { id: 17, key: 'complemento', label: 'Complemento', section: 'CORE', group: 'A2', sourceKey: 'receita_cnpj' },
  { id: 18, key: 'bairro', label: 'Bairro', section: 'CORE', group: 'A2', sourceKey: 'receita_cnpj' },
  { id: 19, key: 'cep', label: 'CEP', section: 'CORE', group: 'A2', sourceKey: 'receita_cnpj' },
  { id: 20, key: 'municipio', label: 'Município', section: 'CORE', group: 'A2', sourceKey: 'receita_cnpj' },
  { id: 21, key: 'uf', label: 'UF', section: 'CORE', group: 'A2', sourceKey: 'receita_cnpj' },
  { id: 22, key: 'ddd_telefone_1', label: 'DDD Telefone 1', section: 'CORE', group: 'A2', sourceKey: 'receita_cnpj' },
  { id: 23, key: 'telefone_1', label: 'Telefone 1', section: 'CORE', group: 'A2', sourceKey: 'receita_cnpj' },
  { id: 24, key: 'email', label: 'E-mail', section: 'CORE', group: 'A2', sourceKey: 'receita_cnpj' },
  { id: 25, key: 'optante_simples', label: 'Optante Simples Nacional (situação)', section: 'CORE', group: 'A3', sourceKey: 'receita_simples' },
  { id: 26, key: 'data_opcao_simples', label: 'Data de Opção Simples', section: 'CORE', group: 'A3', sourceKey: 'receita_simples' },
  { id: 27, key: 'data_exclusao_simples', label: 'Data de Exclusão do Simples', section: 'CORE', group: 'A3', sourceKey: 'receita_simples' },
  { id: 28, key: 'motivo_exclusao_simples', label: 'Motivo da Exclusão do Simples', section: 'CORE', group: 'A3', sourceKey: 'receita_simples' },
  { id: 29, key: 'optante_simei', label: 'Optante SIMEI (MEI)', section: 'CORE', group: 'A3', sourceKey: 'receita_simples' },
  { id: 30, key: 'data_opcao_simei', label: 'Data de Opção SIMEI', section: 'CORE', group: 'A3', sourceKey: 'receita_simples' },
  { id: 31, key: 'sublimite_icms', label: 'Sublimite ICMS (Simples)', section: 'CORE', group: 'A3', sourceKey: 'receita_simples' },
  { id: 32, key: 'pncp_licitacoes_vencidas', label: 'Licitações vencidas (quantidade)', section: 'CORE', group: 'A4', sourceKey: 'pncp' },
  { id: 33, key: 'pncp_contratos_vigentes', label: 'Contratos vigentes (quantidade)', section: 'CORE', group: 'A4', sourceKey: 'pncp' },
  { id: 34, key: 'pncp_valor_total_contratado', label: 'Valor total contratado (vigentes)', section: 'CORE', group: 'A4', sourceKey: 'pncp' },
  { id: 35, key: 'pncp_orgao_maior_contratacao', label: 'Órgão com maior contratação', section: 'CORE', group: 'A4', sourceKey: 'pncp' },
  { id: 36, key: 'pncp_aditivos_quantidade', label: 'Aditivos contratuais (quantidade)', section: 'CORE', group: 'A4', sourceKey: 'pncp' },
  { id: 37, key: 'pncp_sancoes_quantidade', label: 'Sanções (quantidade)', section: 'CORE', group: 'A4', sourceKey: 'pncp' },
  { id: 38, key: 'pncp_sancao_mais_grave', label: 'Sanção mais grave', section: 'CORE', group: 'A4', sourceKey: 'pncp' },
  { id: 39, key: 'socio_1_nome', label: 'Nome Sócio 1', section: 'GOVERNANCA', group: 'B1', sourceKey: 'receita_cnpj' },
  { id: 40, key: 'socio_1_qualificacao', label: 'Qualificação Sócio 1', section: 'GOVERNANCA', group: 'B1', sourceKey: 'receita_cnpj' },
  { id: 41, key: 'socio_1_cpf', label: 'CPF Sócio 1', section: 'GOVERNANCA', group: 'B1', sourceKey: 'receita_cnpj' },
  { id: 42, key: 'socio_1_data_entrada', label: 'Data de Entrada Sócio 1', section: 'GOVERNANCA', group: 'B1', sourceKey: 'receita_cnpj' },
  { id: 43, key: 'socio_2_nome', label: 'Nome Sócio 2', section: 'GOVERNANCA', group: 'B1', sourceKey: 'receita_cnpj' },
  { id: 44, key: 'socio_2_qualificacao', label: 'Qualificação Sócio 2', section: 'GOVERNANCA', group: 'B1', sourceKey: 'receita_cnpj' },
  { id: 45, key: 'socio_2_cpf', label: 'CPF Sócio 2', section: 'GOVERNANCA', group: 'B1', sourceKey: 'receita_cnpj' },
  { id: 46, key: 'socio_2_data_entrada', label: 'Data de Entrada Sócio 2', section: 'GOVERNANCA', group: 'B1', sourceKey: 'receita_cnpj' },
  { id: 47, key: 'cndt_situacao', label: 'CNDT (situação)', section: 'GOVERNANCA', group: 'B2', sourceKey: 'tst_cndt' },
  { id: 48, key: 'cndt_data_emissao', label: 'CNDT (data de emissão)', section: 'GOVERNANCA', group: 'B2', sourceKey: 'tst_cndt' },
  { id: 49, key: 'cnd_federal_situacao', label: 'CND Federal (situação)', section: 'GOVERNANCA', group: 'B2', sourceKey: 'receita_cnd' },
  { id: 50, key: 'cnd_federal_validade', label: 'CND Federal (validade)', section: 'GOVERNANCA', group: 'B2', sourceKey: 'receita_cnd' },
  { id: 51, key: 'crf_situacao', label: 'CRF/FGTS (situação)', section: 'GOVERNANCA', group: 'B2', sourceKey: 'caixa_crf' },
  { id: 52, key: 'crf_validade', label: 'CRF/FGTS (validade)', section: 'GOVERNANCA', group: 'B2', sourceKey: 'caixa_crf' },
  { id: 53, key: 'pgfn_inscricoes_quantidade', label: 'PGFN – Inscrições em Dívida Ativa (quantidade)', section: 'GOVERNANCA', group: 'B2', sourceKey: 'pgfn' },
  { id: 54, key: 'pgfn_valor_total', label: 'PGFN – Valor consolidado (total)', section: 'GOVERNANCA', group: 'B2', sourceKey: 'pgfn' },
  { id: 55, key: 'pgfn_situacao_predominante', label: 'PGFN – Situação predominante', section: 'GOVERNANCA', group: 'B2', sourceKey: 'pgfn' },
  { id: 56, key: 'pgfn_parcelamentos_quantidade', label: 'PGFN – Parcelamentos (quantidade)', section: 'GOVERNANCA', group: 'B2', sourceKey: 'pgfn' },
  { id: 57, key: 'caged_empregados_ativos', label: 'CAGED – Total de empregados ativos', section: 'SOCIAL', group: 'C', sourceKey: 'caged' },
  { id: 58, key: 'caged_admissoes_12m', label: 'CAGED – Admissões (12 meses)', section: 'SOCIAL', group: 'C', sourceKey: 'caged' },
  { id: 59, key: 'caged_desligamentos_12m', label: 'CAGED – Desligamentos (12 meses)', section: 'SOCIAL', group: 'C', sourceKey: 'caged' },
  { id: 60, key: 'caged_saldo_12m', label: 'CAGED – Saldo líquido (12 meses)', section: 'SOCIAL', group: 'C', sourceKey: 'caged' },
  { id: 61, key: 'rais_faixa_salarial_media', label: 'RAIS – Faixa salarial média', section: 'SOCIAL', group: 'C', sourceKey: 'rais' },
  { id: 62, key: 'rais_vinculos_ativos', label: 'RAIS – Total de vínculos ativos', section: 'SOCIAL', group: 'C', sourceKey: 'rais' },
  { id: 63, key: 'rais_percentual_mulheres', label: 'RAIS – % mulheres', section: 'SOCIAL', group: 'C', sourceKey: 'rais' },
  { id: 64, key: 'rais_percentual_pcd', label: 'RAIS – % pessoas com deficiência', section: 'SOCIAL', group: 'C', sourceKey: 'rais' },
  { id: 65, key: 'mte_autos_infracao', label: 'MTE – Autos de infração trabalhista (quantidade)', section: 'SOCIAL', group: 'C', sourceKey: 'mte' },
  { id: 66, key: 'mte_valor_multas', label: 'MTE – Valor total de multas trabalhistas', section: 'SOCIAL', group: 'C', sourceKey: 'mte' },
  { id: 67, key: 'mte_resgates_trabalho_escravo', label: 'MTE – Resgates de trabalho análogo à escravidão', section: 'SOCIAL', group: 'C', sourceKey: 'mte' },
  { id: 68, key: 'mte_acidentes_trabalho', label: 'MTE – Acidentes de trabalho notificados', section: 'SOCIAL', group: 'C', sourceKey: 'mte' },
  { id: 69, key: 'ibama_autos_infracao', label: 'IBAMA – Autos de infração ambiental (quantidade)', section: 'AMBIENTAL', group: 'D', sourceKey: 'ibama' },
  { id: 70, key: 'ibama_valor_multas', label: 'IBAMA – Valor total de multas ambientais', section: 'AMBIENTAL', group: 'D', sourceKey: 'ibama' },
  { id: 71, key: 'ibama_embargos_ativos', label: 'IBAMA – Embargos ambientais ativos', section: 'AMBIENTAL', group: 'D', sourceKey: 'ibama' },
  { id: 72, key: 'ibama_regularidade', label: 'IBAMA – Situação de regularidade ambiental', section: 'AMBIENTAL', group: 'D', sourceKey: 'ibama' },
  { id: 73, key: 'licenca_ambiental_possui', label: 'Licença Ambiental – possui?', section: 'AMBIENTAL', group: 'D', sourceKey: 'ibama' },
  { id: 74, key: 'licenca_ambiental_tipo', label: 'Licença Ambiental – tipo', section: 'AMBIENTAL', group: 'D', sourceKey: 'ibama' },
  { id: 75, key: 'licenca_ambiental_validade', label: 'Licença Ambiental – validade', section: 'AMBIENTAL', group: 'D', sourceKey: 'ibama' },
  { id: 76, key: 'ctf_app_situacao', label: 'CTF/APP – situação', section: 'AMBIENTAL', group: 'D', sourceKey: 'ctf' },
  { id: 77, key: 'ctf_app_categoria', label: 'CTF/APP – categoria', section: 'AMBIENTAL', group: 'D', sourceKey: 'ctf' },
  { id: 78, key: 'sinaflor_registro', label: 'SINAFLOR – uso de recursos florestais (registro/situação)', section: 'AMBIENTAL', group: 'D', sourceKey: 'sinflor' },
  { id: 79, key: 'prodes_area_desmatamento', label: 'PRODES – área com desmatamento detectado', section: 'AMBIENTAL', group: 'D', sourceKey: 'prodes' },
  { id: 80, key: 'icmbio_embargo_ocorrencia', label: 'ICMBio – embargo/ocorrência em área protegida', section: 'AMBIENTAL', group: 'D', sourceKey: 'icmbio' }
];
